// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvQpBZIOHLgmj4bbE0XcjyTdxDVd6N800',
    appId: '1:398136970501:web:ed1f4a97988ea9fb5efb6c',
    messagingSenderId: '398136970501',
    projectId: 'micetap-f3c73',
    authDomain: 'micetap-f3c73.firebaseapp.com',
    storageBucket: 'micetap-f3c73.firebasestorage.app',
    measurementId: 'G-TGGSG1B32N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCinBdDxEVP-uNPnTzcelNLkDgNS4wXh_c',
    appId: '1:398136970501:android:d2957c99c7f187645efb6c',
    messagingSenderId: '398136970501',
    projectId: 'micetap-f3c73',
    storageBucket: 'micetap-f3c73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDZTck-W2x7JnVuKReypQru4auEogR4A',
    appId: '1:398136970501:ios:ef5a22103889f8d45efb6c',
    messagingSenderId: '398136970501',
    projectId: 'micetap-f3c73',
    storageBucket: 'micetap-f3c73.firebasestorage.app',
    iosBundleId: 'com.example.micetapV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdDZTck-W2x7JnVuKReypQru4auEogR4A',
    appId: '1:398136970501:ios:ef5a22103889f8d45efb6c',
    messagingSenderId: '398136970501',
    projectId: 'micetap-f3c73',
    storageBucket: 'micetap-f3c73.firebasestorage.app',
    iosBundleId: 'com.example.micetapV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvQpBZIOHLgmj4bbE0XcjyTdxDVd6N800',
    appId: '1:398136970501:web:e80b6c85d475ea4d5efb6c',
    messagingSenderId: '398136970501',
    projectId: 'micetap-f3c73',
    authDomain: 'micetap-f3c73.firebaseapp.com',
    storageBucket: 'micetap-f3c73.firebasestorage.app',
    measurementId: 'G-TMZPJ6RPSZ',
  );
}
