// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2O4wULnFBwnKIkD4UnHvOC1pwNHgMR-4',
    appId: '1:1093111708053:web:b4a87b5cd34d5178f1de9c',
    messagingSenderId: '1093111708053',
    projectId: 'micetapv2',
    authDomain: 'micetapv2.firebaseapp.com',
    storageBucket: 'micetapv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0zlOjqroHHPeor_-mCINS1fF9v9vvxW0',
    appId: '1:1093111708053:android:fc7f2e2890dbfafef1de9c',
    messagingSenderId: '1093111708053',
    projectId: 'micetapv2',
    storageBucket: 'micetapv2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2O4wULnFBwnKIkD4UnHvOC1pwNHgMR-4',
    appId: '1:1093111708053:web:16645b96522820e7f1de9c',
    messagingSenderId: '1093111708053',
    projectId: 'micetapv2',
    authDomain: 'micetapv2.firebaseapp.com',
    storageBucket: 'micetapv2.firebasestorage.app',
  );
}
